name: EasyPref CI
on: 
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.28.0
        with:
          api-level: 19
          arch: x86
          profile: Nexus 6
          script: ./gradlew connectedCheck
          # script: ./gradlew app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.sample.easyprefs.kotlin.TestSuite
